SELECT 'TB_CLIENTES_CORE' AS tabla, COUNT_BIG(*) AS cantidad
FROM dbo.TB_CLIENTES_CORE

UNION ALL

SELECT 'TB_PRODUCTOS_CAT', COUNT_BIG(*)
FROM dbo.TB_PRODUCTOS_CAT

UNION ALL

SELECT 'TB_MOV_FINANCIEROS', COUNT_BIG(*)
FROM dbo.TB_MOV_FINANCIEROS

UNION ALL

SELECT 'TB_OBLIGACIONES', COUNT_BIG(*)
FROM dbo.TB_OBLIGACIONES

UNION ALL

SELECT 'TB_SUCURSALES_RED', COUNT_BIG(*)
FROM dbo.TB_SUCURSALES_RED

UNION ALL

SELECT 'TB_COMISIONES_LOG', COUNT_BIG(*)
FROM dbo.TB_COMISIONES_LOG;